language: java
sudo: false
script: mvn clean verify -Pskip-ui-tests
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
deploy:
  # Deploy to GitHub releases if the master branch has been tagged
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/net.resheim.eclipse.timekeeper-site/target/net.resheim.eclipse.timekeeper-*.zip
  api_key:
    secure:  TrtpdW5MvmiovgwbyXM4I9Dqm4ZLgSi8PQGaPVeaXNbJdiK//F7TB3fPmBhaQWQB/irEGNCvZhBZIEsp8YMRy0d5Trmq3uRHy90Hu278colkb5lzyQeeRVAXcmrJFYlfATM4y90+qrp9+8Wlw62UA4NPcaYybzLJYo4Xb30x2hQ=
  overwrite: true
  on:
    repo: turesheim/eclipse-timekeeper
    tags: true
    branch: master
