language: java
dist: trusty
sudo: false

env:
  global:  
    - DISPLAY=:99.0  
before_install:  
  - sh -e /etc/init.d/xvfb start - sleep 10 

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify -Pother-os -Dtycho.localArtifacts=ignore
  - sonar-scanner
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "turesheim-github"
    token:
      secure: "ASUilEjJT5fYjMN6Cy5gVeY1fuKiIwEKLX9sxPltAowFABpzzimgLy+Ytbvh1GLsqnCXtVOYSkcClpNHezkuJwVMopj/IQiVl3cB9Qm3BySCgsQVPWHy2+DZ/sMMVMoVdtiQaycP3a8GY3tbi6Wofbb090vmPHNcn13AWEWXOBA="
deploy:
  # Deploy to GitHub releases if the master branch has been tagged
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/net.resheim.eclipse.timekeeper-site/target/net.resheim.eclipse.timekeeper-*.zip
  api_key:
    secure:  TrtpdW5MvmiovgwbyXM4I9Dqm4ZLgSi8PQGaPVeaXNbJdiK//F7TB3fPmBhaQWQB/irEGNCvZhBZIEsp8YMRy0d5Trmq3uRHy90Hu278colkb5lzyQeeRVAXcmrJFYlfATM4y90+qrp9+8Wlw62UA4NPcaYybzLJYo4Xb30x2hQ=
  overwrite: true
  on:
    repo: turesheim/eclipse-timekeeper
    tags: true
    branch: master
